name: Check pull request

on:
  pull_request:

jobs:
  development-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build with Gradle
        run: ./gradlew build